"use strict";

/* strom web GUI — Steam-like catalog browser.
 *
 * Loads web/catalog.json (Steam-enriched, generated by
 * scripts/fetch-steam-metadata.py). If that is missing it degrades to the
 * always-present web/games.json, deriving a name + lutris banner per slug so
 * the catalog still renders. Launching a game hands off to the `strom://`
 * URI scheme, which the desktop's XDG handler (pkgs/strom-launch) turns into
 * `nix run` — a browser cannot spawn processes itself, so the real
 * download/build progress bar lives in that native launcher window. */

const CATALOG_URL = "../catalog.json";
const GAMES_URL = "../games.json";
const LUTRIS_BANNER = (slug) => `https://lutris.net/games/banner/${slug}.jpg`;

// Chip order; unknown runtimes still work, appended after these.
const RUNTIMES = ["proton", "native", "custom", "retroarch", "pcsx2", "dosbox"];

/* Player-mode feature buckets. Each maps a friendly label (what the user
 * filters on) to the set of Steam "category" descriptions that imply it —
 * mirroring how Steam groups its store filters. A game belongs to a bucket
 * when any of its tags match. */
const FEATURES = [
  ["Single-player", ["Single-player"]],
  ["Online multiplayer", ["Multi-player", "Online PvP", "Cross-Platform Multiplayer"]],
  ["Local multiplayer", ["Shared/Split Screen", "Shared/Split Screen PvP", "LAN PvP"]],
  ["Online co-op", ["Online Co-op"]],
  ["Local co-op", ["Shared/Split Screen Co-op", "LAN Co-op"]],
  ["Remote Play Together", ["Remote Play Together"]],
  ["PvP", ["PvP", "Online PvP", "Shared/Split Screen PvP", "LAN PvP"]],
];

// Facet groups, evaluated as OR within a group and AND across groups, the way
// Steam's store filters behave. `values` returns a game's values for the group;
// `label` maps an internal value to its display text (defaults to identity).
const SOURCE_LABEL = { steam: "Steam", community: "Community" };
const GROUPS = [
  { key: "runtime", title: "Runtime", values: (e) => [e.runtime] },
  { key: "genre", title: "Genre", values: (e) => e.genres || [] },
  { key: "feature", title: "Features", values: (e) => e._features },
  {
    key: "source",
    title: "Metadata",
    values: (e) => [e._source],
    label: (v) => SOURCE_LABEL[v] || v,
  },
];

const el = {
  search: document.getElementById("search"),
  count: document.getElementById("count"),
  clear: document.getElementById("clear-filters"),
  facets: document.getElementById("facets"),
  layout: document.getElementById("layout"),
  library: document.getElementById("library"),
  detail: document.getElementById("detail"),
  lightbox: document.getElementById("lightbox"),
  lightboxImg: document.getElementById("lightbox-img"),
  overlay: document.getElementById("overlay"),
  overlayTitle: document.getElementById("overlay-title"),
  overlayClose: document.getElementById("overlay-close"),
  overlayCmd: document.getElementById("overlay-cmd"),
  overlayCopy: document.getElementById("overlay-copy"),
};

// Public flake the strom:// handler launches from; also shown as the manual
// fallback command. Keep in sync with pkgs/strom-launch default STROM_FLAKE.
const FLAKE_REF = "github:kraftwerk-gaming/strom";

const state = {
  catalog: {}, // slug -> entry
  slugs: [], // sorted by name
  query: "",
  f: { runtime: new Set(), genre: new Set(), feature: new Set(), source: new Set() },
  open: new Set(["Runtime", "Genre", "Features"]), // expanded facet groups
  lightbox: null, // { list, index } when fullscreen image open
};

/* ---------- data loading ---------- */

function deriveName(slug, description) {
  let name = description || slug.replace(/-/g, " ");
  name = name.replace(/\s*\([^()]*\)\s*$/, "").trim();
  return name || slug;
}

function fromGamesJson(games) {
  const out = {};
  for (const [slug, m] of Object.entries(games)) {
    out[slug] = {
      name: deriveName(slug, m.description),
      runtime: m.runtime || "unknown",
      short: m.description || "",
      long: "",
      genres: [],
      tags: [],
      year: null,
      developers: [],
      hero: LUTRIS_BANNER(slug),
      screenshots: [],
      lutris: `https://lutris.net/games/${slug}/`,
    };
  }
  return out;
}

async function loadCatalog() {
  try {
    const r = await fetch(CATALOG_URL, { cache: "no-cache" });
    if (r.ok) return await r.json();
  } catch (_) {
    /* fall through to games.json */
  }
  const r = await fetch(GAMES_URL, { cache: "no-cache" });
  if (!r.ok) throw new Error("could not load catalog or games.json");
  return fromGamesJson(await r.json());
}

// Precompute, once at load: which feature buckets each game satisfies, and
// whether its metadata came from Steam or was curated manually (no Steam match).
function annotate(entry) {
  const tags = new Set(entry.tags || []);
  entry._features = FEATURES.filter(([, cats]) => cats.some((c) => tags.has(c))).map(
    ([label]) => label,
  );
  entry._source = entry.steam_appid ? "steam" : "community";
}

/* ---------- helpers ---------- */

function runtimeClass(rt) {
  return RUNTIMES.includes(rt) ? `rt-${rt}` : "rt-unknown";
}

// True when entry satisfies all active facets (skipping `skipKey`, used for
// faceted counts) and the search query.
function passes(entry, skipKey) {
  for (const g of GROUPS) {
    if (g.key === skipKey) continue;
    const sel = state.f[g.key];
    if (!sel.size) continue;
    if (!g.values(entry).some((v) => sel.has(v))) return false;
  }
  if (state.query) {
    const hay = [entry.name, entry.runtime, ...(entry.genres || []), ...entry._features]
      .join(" ")
      .toLowerCase();
    if (!hay.includes(state.query)) return false;
  }
  return true;
}

function activeFilterCount() {
  return GROUPS.reduce((n, g) => n + state.f[g.key].size, 0);
}

function visibleSlugs() {
  return state.slugs.filter((s) => passes(state.catalog[s], null));
}

/* ---------- facets sidebar ---------- */

// Count of games for option `value` in group `g`, given every OTHER active
// facet + search — Steam's "this many match if you also pick this" counts.
function optionCount(g, value) {
  let n = 0;
  for (const s of state.slugs) {
    const e = state.catalog[s];
    if (passes(e, g.key) && g.values(e).includes(value)) n++;
  }
  return n;
}

// Which option values exist for a group, in display order.
function groupOptions(g) {
  if (g.key === "feature") {
    return FEATURES.map(([label]) => label);
  }
  const present = new Set();
  for (const s of state.slugs) for (const v of g.values(state.catalog[s])) present.add(v);
  const vals = [...present];
  if (g.key === "runtime") {
    vals.sort((a, b) => {
      const ia = RUNTIMES.indexOf(a);
      const ib = RUNTIMES.indexOf(b);
      return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
    });
  } else {
    vals.sort((a, b) => a.localeCompare(b));
  }
  return vals;
}

function renderFacets() {
  el.facets.replaceChildren();
  for (const g of GROUPS) {
    const sel = state.f[g.key];
    const rows = [];
    for (const value of groupOptions(g)) {
      const checked = sel.has(value);
      const count = optionCount(g, value);
      if (count === 0 && !checked) continue; // hide impossible options, Steam-style

      const row = document.createElement("label");
      row.className = "facet-row";
      const box = document.createElement("input");
      box.type = "checkbox";
      box.checked = checked;
      box.addEventListener("change", () => {
        if (box.checked) sel.add(value);
        else sel.delete(value);
        renderFacets();
        renderLibrary();
        syncClear();
      });
      const name = document.createElement("span");
      name.className = "facet-name";
      if (g.key === "runtime") {
        const badge = document.createElement("span");
        badge.className = `badge ${runtimeClass(value)}`;
        badge.textContent = value;
        name.appendChild(badge);
      } else {
        name.textContent = g.label ? g.label(value) : value;
      }
      const cnt = document.createElement("span");
      cnt.className = "facet-count";
      cnt.textContent = String(count);
      row.append(box, name, cnt);
      rows.push(row);
    }
    if (rows.length === 0) continue;

    const group = document.createElement("details");
    group.className = "facet-group";
    group.open = state.open.has(g.title);
    group.addEventListener("toggle", () => {
      if (group.open) state.open.add(g.title);
      else state.open.delete(g.title);
    });
    const summary = document.createElement("summary");
    summary.textContent = g.title;
    if (sel.size) {
      const b = document.createElement("span");
      b.className = "facet-active";
      b.textContent = String(sel.size);
      summary.appendChild(b);
    }
    group.appendChild(summary);
    for (const r of rows) group.appendChild(r);
    el.facets.appendChild(group);
  }
}

function syncClear() {
  el.clear.hidden = activeFilterCount() === 0;
}

function clearFilters() {
  for (const g of GROUPS) state.f[g.key].clear();
  renderFacets();
  renderLibrary();
  syncClear();
}

/* ---------- library grid ---------- */

function makeBadge(rt) {
  const b = document.createElement("span");
  b.className = `badge ${runtimeClass(rt)}`;
  b.textContent = rt;
  return b;
}

// Marker shown on games whose metadata was hand-curated rather than pulled
// from Steam, so it is clear which entries are not first-party Steam data.
function makeSourceBadge() {
  const b = document.createElement("span");
  b.className = "badge community";
  b.textContent = "community";
  b.title = "Metadata curated for strom — not from Steam";
  return b;
}

function makeCard(slug) {
  const e = state.catalog[slug];
  const card = document.createElement("a");
  card.className = "card";
  card.href = `#${slug}`;
  card.setAttribute("aria-label", `${e.name} (${e.runtime})`);

  const img = document.createElement("img");
  img.loading = "lazy";
  img.alt = "";
  img.src = e.hero || LUTRIS_BANNER(slug);
  img.addEventListener("error", () => {
    img.replaceWith(
      Object.assign(document.createElement("div"), {
        className: "fallback",
        textContent: e.name,
      }),
    );
  });
  card.appendChild(img);

  const meta = document.createElement("div");
  meta.className = "overlay-meta";
  const title = document.createElement("span");
  title.className = "title";
  title.textContent = e.name;
  meta.append(title, makeBadge(e.runtime));
  if (e._source === "community") meta.appendChild(makeSourceBadge());
  card.appendChild(meta);
  return card;
}

function renderLibrary() {
  const slugs = visibleSlugs();
  el.count.textContent = `${slugs.length} / ${state.slugs.length} games`;
  el.library.replaceChildren();
  if (slugs.length === 0) {
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = "No games match your filters.";
    el.library.appendChild(p);
    return;
  }
  const frag = document.createDocumentFragment();
  for (const slug of slugs) frag.appendChild(makeCard(slug));
  el.library.appendChild(frag);
}

/* ---------- detail view ---------- */

function textSpan(t) {
  const s = document.createElement("span");
  s.textContent = t;
  return s;
}

function metaRow(e) {
  const row = document.createElement("div");
  row.className = "meta-row";
  const parts = [makeBadge(e.runtime)];
  if (e._source === "community") parts.push(makeSourceBadge());
  if (e.year) parts.push(textSpan(String(e.year)));
  if (e.genres && e.genres.length) parts.push(textSpan(e.genres.join(", ")));
  if (e.developers && e.developers.length) parts.push(textSpan(e.developers.join(", ")));
  parts.forEach((node, i) => {
    if (i > 0) {
      const dot = document.createElement("span");
      dot.className = "dot";
      dot.textContent = "•";
      row.appendChild(dot);
    }
    row.appendChild(node);
  });
  return row;
}

function featureChips(e) {
  if (!e._features || e._features.length === 0) return null;
  const wrap = document.createElement("div");
  wrap.className = "feature-chips";
  for (const f of e._features) {
    const c = document.createElement("span");
    c.className = "feature-chip";
    c.textContent = f;
    wrap.appendChild(c);
  }
  return wrap;
}

function openLightbox(list, index) {
  state.lightbox = { list, index };
  el.lightboxImg.src = list[index];
  el.lightbox.hidden = false;
}

function closeLightbox() {
  state.lightbox = null;
  el.lightbox.hidden = true;
  el.lightboxImg.src = "";
}

function stepLightbox(delta) {
  if (!state.lightbox) return;
  const { list } = state.lightbox;
  const index = (state.lightbox.index + delta + list.length) % list.length;
  state.lightbox.index = index;
  el.lightboxImg.src = list[index];
}

function navButton(cls, glyph, label, onClick) {
  const b = document.createElement("button");
  b.type = "button";
  b.className = `carousel-nav ${cls}`;
  b.textContent = glyph;
  b.setAttribute("aria-label", label);
  b.addEventListener("click", onClick);
  return b;
}

// Steam-style single-image carousel: one large stage with prev/next controls
// and a thumbnail strip, so the gallery sits at the top of the detail page
// without forcing a scroll. Index state lives in this closure; the lightbox
// keeps its own copy so fullscreen viewing stays independent.
function makeCarousel(e) {
  if (!e.screenshots || e.screenshots.length === 0) return null;
  const list = e.screenshots;
  let index = 0;

  const carousel = document.createElement("div");
  carousel.className = "carousel";

  const stage = document.createElement("div");
  stage.className = "carousel-stage";

  const main = document.createElement("img");
  main.className = "carousel-main";
  main.alt = `${e.name} screenshot`;
  main.addEventListener("click", () => openLightbox(list, index));
  stage.appendChild(main);

  const thumbs = document.createElement("div");
  thumbs.className = "carousel-thumbs";
  const thumbImgs = [];

  function show(i) {
    index = (i + list.length) % list.length;
    main.src = list[index];
    if (counter) counter.textContent = `${index + 1} / ${list.length}`;
    thumbImgs.forEach((t, j) => t.classList.toggle("active", j === index));
    const active = thumbImgs[index];
    if (active) active.scrollIntoView({ inline: "nearest", block: "nearest" });
  }

  let counter = null;
  if (list.length > 1) {
    counter = document.createElement("span");
    counter.className = "carousel-counter";

    stage.appendChild(navButton("prev", "‹", "Previous screenshot", () => show(index - 1)));
    stage.appendChild(navButton("next", "›", "Next screenshot", () => show(index + 1)));
    stage.appendChild(counter);

    stage.tabIndex = 0;
    stage.setAttribute("role", "group");
    stage.setAttribute("aria-label", "Screenshot carousel, use arrow keys");
    stage.addEventListener("keydown", (ev) => {
      if (ev.key === "ArrowLeft") {
        ev.preventDefault();
        show(index - 1);
      } else if (ev.key === "ArrowRight") {
        ev.preventDefault();
        show(index + 1);
      }
    });

    list.forEach((src, i) => {
      const t = document.createElement("img");
      t.loading = "lazy";
      t.src = src;
      t.alt = `${e.name} screenshot ${i + 1}`;
      t.addEventListener("click", () => show(i));
      thumbImgs.push(t);
      thumbs.appendChild(t);
    });
  }

  carousel.appendChild(stage);
  if (list.length > 1) carousel.appendChild(thumbs);
  show(0);
  return carousel;
}

function renderDetail(slug) {
  const e = state.catalog[slug];
  el.detail.replaceChildren();
  el.detail.dataset.open = "1";
  el.detail.hidden = false;
  el.layout.hidden = true;

  // Ambient banner behind the page; the body overlaps its faded lower edge so
  // the title sits over the artwork like the previous design.
  const hero = document.createElement("div");
  hero.className = "detail-hero";
  hero.style.backgroundImage = `url("${e.hero || LUTRIS_BANNER(slug)}")`;

  const back = document.createElement("button");
  back.className = "detail-back";
  back.type = "button";
  back.textContent = "← Library";
  back.addEventListener("click", () => {
    location.hash = "";
  });
  hero.appendChild(back);
  el.detail.appendChild(hero);

  const body = document.createElement("div");
  body.className = "detail-body";

  const h1 = document.createElement("h1");
  h1.textContent = e.name;
  body.appendChild(h1);
  body.appendChild(metaRow(e));

  // Steam-style split: media (carousel) leads on the left, the play button and
  // quick facts sit in a sidebar on the right. The long description spans the
  // full width underneath so screenshots never get pushed below the fold.
  const grid = document.createElement("div");
  grid.className = "detail-grid";

  const media = document.createElement("div");
  media.className = "detail-media";
  const carousel = makeCarousel(e);
  if (carousel) {
    media.appendChild(carousel);
  } else {
    const banner = document.createElement("div");
    banner.className = "detail-banner";
    banner.style.backgroundImage = `url("${e.hero || LUTRIS_BANNER(slug)}")`;
    media.appendChild(banner);
  }
  grid.appendChild(media);

  const side = document.createElement("div");
  side.className = "detail-side";

  const play = document.createElement("button");
  play.className = "play";
  play.type = "button";
  play.textContent = "Play";
  play.addEventListener("click", () => launch(slug, e.name));
  side.appendChild(play);

  const chips = featureChips(e);
  if (chips) side.appendChild(chips);

  if (e.short) {
    const p = document.createElement("p");
    p.className = "short";
    p.textContent = e.short;
    side.appendChild(p);
  }
  grid.appendChild(side);
  body.appendChild(grid);

  if (e.long && e.long !== e.short) {
    const p = document.createElement("p");
    p.className = "long";
    p.textContent = e.long;
    body.appendChild(p);
  }

  el.detail.appendChild(body);
  back.focus();
  window.scrollTo(0, 0);
}

function closeDetail() {
  el.detail.hidden = true;
  el.detail.dataset.open = "0";
  el.layout.hidden = false;
}

/* ---------- launch ---------- */

function launch(slug, name) {
  el.overlayTitle.textContent = `Launching ${name}…`;
  el.overlayCmd.textContent = `nix run ${FLAKE_REF}#${slug}`;
  el.overlayCopy.textContent = "Copy";
  el.overlay.hidden = false;
  el.overlayClose.focus();
  // Hand off to the XDG scheme handler. Fire-and-forget: the browser cannot
  // observe the nix download/build, so progress is shown in the native
  // launcher window spawned by pkgs/strom-launch. If no handler is registered
  // the browser does nothing — hence the copyable fallback command.
  window.location.href = `strom://${encodeURIComponent(slug)}`;
}

function closeOverlay() {
  el.overlay.hidden = true;
}

/* ---------- routing ---------- */

function router() {
  const slug = decodeURIComponent(location.hash.replace(/^#/, ""));
  if (slug && state.catalog[slug]) {
    renderDetail(slug);
  } else {
    closeDetail();
  }
}

/* ---------- init ---------- */

function wireEvents() {
  el.search.addEventListener("input", () => {
    state.query = el.search.value.trim().toLowerCase();
    renderFacets();
    renderLibrary();
  });
  el.clear.addEventListener("click", clearFilters);
  el.overlayClose.addEventListener("click", closeOverlay);
  el.overlayCopy.addEventListener("click", async () => {
    try {
      await navigator.clipboard.writeText(el.overlayCmd.textContent);
      el.overlayCopy.textContent = "Copied";
    } catch (_) {
      el.overlayCopy.textContent = "Copy failed";
    }
  });
  el.lightbox.addEventListener("click", closeLightbox);
  document.addEventListener("keydown", (ev) => {
    if (!el.lightbox.hidden) {
      if (ev.key === "ArrowLeft") {
        ev.preventDefault();
        stepLightbox(-1);
      } else if (ev.key === "ArrowRight") {
        ev.preventDefault();
        stepLightbox(1);
      } else if (ev.key === "Escape") {
        closeLightbox();
      }
      return;
    }
    if (ev.key !== "Escape") return;
    if (!el.overlay.hidden) {
      closeOverlay();
    } else if (el.detail.dataset.open === "1") {
      location.hash = "";
    }
  });
  window.addEventListener("hashchange", router);
}

async function init() {
  try {
    state.catalog = await loadCatalog();
  } catch (err) {
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = `Failed to load catalog: ${err.message}`;
    el.library.replaceChildren(p);
    return;
  }
  for (const e of Object.values(state.catalog)) annotate(e);
  state.slugs = Object.keys(state.catalog).sort((a, b) =>
    state.catalog[a].name.localeCompare(state.catalog[b].name),
  );
  renderFacets();
  renderLibrary();
  syncClear();
  wireEvents();
  router();
}

init();
