"use strict";

/* strom web GUI — Steam-like catalog browser.
 *
 * Loads web/catalog.json (Steam-enriched, generated by
 * scripts/fetch-steam-metadata.py). If that is missing it degrades to the
 * always-present web/games.json, deriving a name + lutris banner per slug so
 * the catalog still renders. Launching a game hands off to the `strom://`
 * URI scheme, which the desktop's XDG handler (pkgs/strom-launch) turns into
 * `nix run` — a browser cannot spawn processes itself, so the real
 * download/build progress bar lives in that native launcher window. */

const CATALOG_URL = "../catalog.json";
const GAMES_URL = "../games.json";
const LUTRIS_BANNER = (slug) => `https://lutris.net/games/banner/${slug}.jpg`;

// Chip order; unknown runtimes still work, appended after these.
const RUNTIMES = ["proton", "native", "custom", "retroarch", "pcsx2", "dosbox"];

/* Player-mode feature buckets. Each maps a friendly label (what the user
 * filters on) to the set of Steam "category" descriptions that imply it —
 * mirroring how Steam groups its store filters. A game belongs to a bucket
 * when any of its tags match. */
const FEATURES = [
  ["Single-player", ["Single-player"]],
  ["Online multiplayer", ["Multi-player", "Online PvP", "Cross-Platform Multiplayer"]],
  ["Local multiplayer", ["Shared/Split Screen", "Shared/Split Screen PvP", "LAN PvP"]],
  ["Online co-op", ["Online Co-op"]],
  ["Local co-op", ["Shared/Split Screen Co-op", "LAN Co-op"]],
  ["Remote Play Together", ["Remote Play Together"]],
  ["PvP", ["PvP", "Online PvP", "Shared/Split Screen PvP", "LAN PvP"]],
];

// Facet groups, evaluated as OR within a group and AND across groups, the way
// Steam's store filters behave. `values` returns a game's values for the group.
const GROUPS = [
  { key: "runtime", title: "Runtime", values: (e) => [e.runtime] },
  { key: "genre", title: "Genre", values: (e) => e.genres || [] },
  { key: "feature", title: "Features", values: (e) => e._features },
];

const el = {
  search: document.getElementById("search"),
  count: document.getElementById("count"),
  clear: document.getElementById("clear-filters"),
  facets: document.getElementById("facets"),
  layout: document.getElementById("layout"),
  library: document.getElementById("library"),
  detail: document.getElementById("detail"),
  lightbox: document.getElementById("lightbox"),
  lightboxImg: document.getElementById("lightbox-img"),
  overlay: document.getElementById("overlay"),
  overlayTitle: document.getElementById("overlay-title"),
  overlayClose: document.getElementById("overlay-close"),
};

const state = {
  catalog: {}, // slug -> entry
  slugs: [], // sorted by name
  query: "",
  f: { runtime: new Set(), genre: new Set(), feature: new Set() },
  open: new Set(["Runtime", "Genre", "Features"]), // expanded facet groups
};

/* ---------- data loading ---------- */

function deriveName(slug, description) {
  let name = description || slug.replace(/-/g, " ");
  name = name.replace(/\s*\([^()]*\)\s*$/, "").trim();
  return name || slug;
}

function fromGamesJson(games) {
  const out = {};
  for (const [slug, m] of Object.entries(games)) {
    out[slug] = {
      name: deriveName(slug, m.description),
      runtime: m.runtime || "unknown",
      short: m.description || "",
      long: "",
      genres: [],
      tags: [],
      year: null,
      developers: [],
      hero: LUTRIS_BANNER(slug),
      screenshots: [],
      lutris: `https://lutris.net/games/${slug}/`,
    };
  }
  return out;
}

async function loadCatalog() {
  try {
    const r = await fetch(CATALOG_URL, { cache: "no-cache" });
    if (r.ok) return await r.json();
  } catch (_) {
    /* fall through to games.json */
  }
  const r = await fetch(GAMES_URL, { cache: "no-cache" });
  if (!r.ok) throw new Error("could not load catalog or games.json");
  return fromGamesJson(await r.json());
}

// Precompute which feature buckets each game satisfies, once, at load.
function annotate(entry) {
  const tags = new Set(entry.tags || []);
  entry._features = FEATURES.filter(([, cats]) => cats.some((c) => tags.has(c))).map(
    ([label]) => label,
  );
}

/* ---------- helpers ---------- */

function runtimeClass(rt) {
  return RUNTIMES.includes(rt) ? `rt-${rt}` : "rt-unknown";
}

// True when entry satisfies all active facets (skipping `skipKey`, used for
// faceted counts) and the search query.
function passes(entry, skipKey) {
  for (const g of GROUPS) {
    if (g.key === skipKey) continue;
    const sel = state.f[g.key];
    if (!sel.size) continue;
    if (!g.values(entry).some((v) => sel.has(v))) return false;
  }
  if (state.query) {
    const hay = [entry.name, entry.runtime, ...(entry.genres || []), ...entry._features]
      .join(" ")
      .toLowerCase();
    if (!hay.includes(state.query)) return false;
  }
  return true;
}

function activeFilterCount() {
  return GROUPS.reduce((n, g) => n + state.f[g.key].size, 0);
}

function visibleSlugs() {
  return state.slugs.filter((s) => passes(state.catalog[s], null));
}

/* ---------- facets sidebar ---------- */

// Count of games for option `value` in group `g`, given every OTHER active
// facet + search — Steam's "this many match if you also pick this" counts.
function optionCount(g, value) {
  let n = 0;
  for (const s of state.slugs) {
    const e = state.catalog[s];
    if (passes(e, g.key) && g.values(e).includes(value)) n++;
  }
  return n;
}

// Which option values exist for a group, in display order.
function groupOptions(g) {
  if (g.key === "feature") {
    return FEATURES.map(([label]) => label);
  }
  const present = new Set();
  for (const s of state.slugs) for (const v of g.values(state.catalog[s])) present.add(v);
  const vals = [...present];
  if (g.key === "runtime") {
    vals.sort((a, b) => {
      const ia = RUNTIMES.indexOf(a);
      const ib = RUNTIMES.indexOf(b);
      return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
    });
  } else {
    vals.sort((a, b) => a.localeCompare(b));
  }
  return vals;
}

function renderFacets() {
  el.facets.replaceChildren();
  for (const g of GROUPS) {
    const sel = state.f[g.key];
    const rows = [];
    for (const value of groupOptions(g)) {
      const checked = sel.has(value);
      const count = optionCount(g, value);
      if (count === 0 && !checked) continue; // hide impossible options, Steam-style

      const row = document.createElement("label");
      row.className = "facet-row";
      const box = document.createElement("input");
      box.type = "checkbox";
      box.checked = checked;
      box.addEventListener("change", () => {
        if (box.checked) sel.add(value);
        else sel.delete(value);
        renderFacets();
        renderLibrary();
        syncClear();
      });
      const name = document.createElement("span");
      name.className = "facet-name";
      if (g.key === "runtime") {
        const badge = document.createElement("span");
        badge.className = `badge ${runtimeClass(value)}`;
        badge.textContent = value;
        name.appendChild(badge);
      } else {
        name.textContent = value;
      }
      const cnt = document.createElement("span");
      cnt.className = "facet-count";
      cnt.textContent = String(count);
      row.append(box, name, cnt);
      rows.push(row);
    }
    if (rows.length === 0) continue;

    const group = document.createElement("details");
    group.className = "facet-group";
    group.open = state.open.has(g.title);
    group.addEventListener("toggle", () => {
      if (group.open) state.open.add(g.title);
      else state.open.delete(g.title);
    });
    const summary = document.createElement("summary");
    summary.textContent = g.title;
    if (sel.size) {
      const b = document.createElement("span");
      b.className = "facet-active";
      b.textContent = String(sel.size);
      summary.appendChild(b);
    }
    group.appendChild(summary);
    for (const r of rows) group.appendChild(r);
    el.facets.appendChild(group);
  }
}

function syncClear() {
  el.clear.hidden = activeFilterCount() === 0;
}

function clearFilters() {
  for (const g of GROUPS) state.f[g.key].clear();
  renderFacets();
  renderLibrary();
  syncClear();
}

/* ---------- library grid ---------- */

function makeBadge(rt) {
  const b = document.createElement("span");
  b.className = `badge ${runtimeClass(rt)}`;
  b.textContent = rt;
  return b;
}

function makeCard(slug) {
  const e = state.catalog[slug];
  const card = document.createElement("a");
  card.className = "card";
  card.href = `#${slug}`;
  card.setAttribute("aria-label", `${e.name} (${e.runtime})`);

  const img = document.createElement("img");
  img.loading = "lazy";
  img.alt = "";
  img.src = e.hero || LUTRIS_BANNER(slug);
  img.addEventListener("error", () => {
    img.replaceWith(
      Object.assign(document.createElement("div"), {
        className: "fallback",
        textContent: e.name,
      }),
    );
  });
  card.appendChild(img);

  const meta = document.createElement("div");
  meta.className = "overlay-meta";
  const title = document.createElement("span");
  title.className = "title";
  title.textContent = e.name;
  meta.append(title, makeBadge(e.runtime));
  card.appendChild(meta);
  return card;
}

function renderLibrary() {
  const slugs = visibleSlugs();
  el.count.textContent = `${slugs.length} / ${state.slugs.length} games`;
  el.library.replaceChildren();
  if (slugs.length === 0) {
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = "No games match your filters.";
    el.library.appendChild(p);
    return;
  }
  const frag = document.createDocumentFragment();
  for (const slug of slugs) frag.appendChild(makeCard(slug));
  el.library.appendChild(frag);
}

/* ---------- detail view ---------- */

function textSpan(t) {
  const s = document.createElement("span");
  s.textContent = t;
  return s;
}

function metaRow(e) {
  const row = document.createElement("div");
  row.className = "meta-row";
  const parts = [makeBadge(e.runtime)];
  if (e.year) parts.push(textSpan(String(e.year)));
  if (e.genres && e.genres.length) parts.push(textSpan(e.genres.join(", ")));
  if (e.developers && e.developers.length) parts.push(textSpan(e.developers.join(", ")));
  parts.forEach((node, i) => {
    if (i > 0) {
      const dot = document.createElement("span");
      dot.className = "dot";
      dot.textContent = "•";
      row.appendChild(dot);
    }
    row.appendChild(node);
  });
  return row;
}

function featureChips(e) {
  if (!e._features || e._features.length === 0) return null;
  const wrap = document.createElement("div");
  wrap.className = "feature-chips";
  for (const f of e._features) {
    const c = document.createElement("span");
    c.className = "feature-chip";
    c.textContent = f;
    wrap.appendChild(c);
  }
  return wrap;
}

function openLightbox(src) {
  el.lightboxImg.src = src;
  el.lightbox.hidden = false;
}

function makeShots(e) {
  if (!e.screenshots || e.screenshots.length === 0) return null;
  const wrap = document.createElement("div");
  wrap.className = "shots";
  for (const src of e.screenshots) {
    const img = document.createElement("img");
    img.loading = "lazy";
    img.src = src;
    img.alt = `${e.name} screenshot`;
    img.tabIndex = 0;
    img.addEventListener("click", () => openLightbox(src));
    img.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter" || ev.key === " ") {
        ev.preventDefault();
        openLightbox(src);
      }
    });
    wrap.appendChild(img);
  }
  return wrap;
}

function renderDetail(slug) {
  const e = state.catalog[slug];
  el.detail.replaceChildren();
  el.detail.dataset.open = "1";
  el.detail.hidden = false;
  el.layout.hidden = true;

  const hero = document.createElement("div");
  hero.className = "detail-hero";
  hero.style.backgroundImage = `url("${e.hero || LUTRIS_BANNER(slug)}")`;

  const back = document.createElement("button");
  back.className = "detail-back";
  back.type = "button";
  back.textContent = "← Library";
  back.addEventListener("click", () => {
    location.hash = "";
  });
  hero.appendChild(back);
  el.detail.appendChild(hero);

  const body = document.createElement("div");
  body.className = "detail-body";

  const h1 = document.createElement("h1");
  h1.textContent = e.name;
  body.appendChild(h1);
  body.appendChild(metaRow(e));

  const play = document.createElement("button");
  play.className = "play";
  play.type = "button";
  play.textContent = "Play";
  play.addEventListener("click", () => launch(slug, e.name));
  body.appendChild(play);

  const chips = featureChips(e);
  if (chips) body.appendChild(chips);

  if (e.short) {
    const p = document.createElement("p");
    p.className = "short";
    p.textContent = e.short;
    body.appendChild(p);
  }
  if (e.long && e.long !== e.short) {
    const p = document.createElement("p");
    p.className = "long";
    p.textContent = e.long;
    body.appendChild(p);
  }
  const shots = makeShots(e);
  if (shots) body.appendChild(shots);

  el.detail.appendChild(body);
  back.focus();
  window.scrollTo(0, 0);
}

function closeDetail() {
  el.detail.hidden = true;
  el.detail.dataset.open = "0";
  el.layout.hidden = false;
}

/* ---------- launch ---------- */

function launch(slug, name) {
  el.overlayTitle.textContent = `Launching ${name}…`;
  el.overlay.hidden = false;
  el.overlayClose.focus();
  // Hand off to the XDG scheme handler. Fire-and-forget: the browser cannot
  // observe the nix download/build, so progress is shown in the native
  // launcher window spawned by pkgs/strom-launch.
  window.location.href = `strom://${encodeURIComponent(slug)}`;
}

function closeOverlay() {
  el.overlay.hidden = true;
}

/* ---------- routing ---------- */

function router() {
  const slug = decodeURIComponent(location.hash.replace(/^#/, ""));
  if (slug && state.catalog[slug]) {
    renderDetail(slug);
  } else {
    closeDetail();
  }
}

/* ---------- init ---------- */

function wireEvents() {
  el.search.addEventListener("input", () => {
    state.query = el.search.value.trim().toLowerCase();
    renderFacets();
    renderLibrary();
  });
  el.clear.addEventListener("click", clearFilters);
  el.overlayClose.addEventListener("click", closeOverlay);
  el.lightbox.addEventListener("click", () => {
    el.lightbox.hidden = true;
    el.lightboxImg.src = "";
  });
  document.addEventListener("keydown", (ev) => {
    if (ev.key !== "Escape") return;
    if (!el.lightbox.hidden) {
      el.lightbox.hidden = true;
      el.lightboxImg.src = "";
    } else if (!el.overlay.hidden) {
      closeOverlay();
    } else if (el.detail.dataset.open === "1") {
      location.hash = "";
    }
  });
  window.addEventListener("hashchange", router);
}

async function init() {
  try {
    state.catalog = await loadCatalog();
  } catch (err) {
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = `Failed to load catalog: ${err.message}`;
    el.library.replaceChildren(p);
    return;
  }
  for (const e of Object.values(state.catalog)) annotate(e);
  state.slugs = Object.keys(state.catalog).sort((a, b) =>
    state.catalog[a].name.localeCompare(state.catalog[b].name),
  );
  renderFacets();
  renderLibrary();
  syncClear();
  wireEvents();
  router();
}

init();
