"use strict";

/* strom web GUI — Steam-like catalog browser.
 *
 * Loads web/catalog.json (Steam-enriched, generated by
 * scripts/fetch-steam-metadata.py). If that is missing it degrades to the
 * always-present web/games.json, deriving a name + lutris banner per slug so
 * the catalog still renders. Launching a game hands off to the `strom://`
 * URI scheme, which the desktop's XDG handler (pkgs/strom-launch) turns into
 * `nix run` — a browser cannot spawn processes itself, so the real
 * download/build progress bar lives in that native launcher window. */

const CATALOG_URL = "../catalog.json";
const GAMES_URL = "../games.json";
const LUTRIS_BANNER = (slug) => `https://lutris.net/games/banner/${slug}.jpg`;

// Chip order; "all" is prepended at render time. Unknown runtimes still work.
const RUNTIMES = ["proton", "native", "custom", "retroarch", "pcsx2", "dosbox"];

const el = {
  search: document.getElementById("search"),
  count: document.getElementById("count"),
  filters: document.getElementById("filters"),
  library: document.getElementById("library"),
  detail: document.getElementById("detail"),
  lightbox: document.getElementById("lightbox"),
  lightboxImg: document.getElementById("lightbox-img"),
  overlay: document.getElementById("overlay"),
  overlayTitle: document.getElementById("overlay-title"),
  overlayClose: document.getElementById("overlay-close"),
};

const state = {
  catalog: {}, // slug -> entry
  slugs: [], // sorted by name
  query: "",
  runtime: "all",
};

/* ---------- data loading ---------- */

function deriveName(slug, description) {
  let name = description || slug.replace(/-/g, " ");
  name = name.replace(/\s*\([^()]*\)\s*$/, "").trim();
  return name || slug;
}

function fromGamesJson(games) {
  const out = {};
  for (const [slug, m] of Object.entries(games)) {
    out[slug] = {
      name: deriveName(slug, m.description),
      runtime: m.runtime || "unknown",
      short: m.description || "",
      long: "",
      genres: [],
      year: null,
      developers: [],
      hero: LUTRIS_BANNER(slug),
      screenshots: [],
      lutris: `https://lutris.net/games/${slug}/`,
    };
  }
  return out;
}

async function loadCatalog() {
  try {
    const r = await fetch(CATALOG_URL, { cache: "no-cache" });
    if (r.ok) return await r.json();
  } catch (_) {
    /* fall through to games.json */
  }
  const r = await fetch(GAMES_URL, { cache: "no-cache" });
  if (!r.ok) throw new Error("could not load catalog or games.json");
  return fromGamesJson(await r.json());
}

/* ---------- helpers ---------- */

function runtimeClass(rt) {
  return RUNTIMES.includes(rt) ? `rt-${rt}` : "rt-unknown";
}

function matches(entry) {
  if (state.runtime !== "all" && entry.runtime !== state.runtime) return false;
  if (!state.query) return true;
  const hay = [entry.name, entry.runtime, ...(entry.genres || [])]
    .join(" ")
    .toLowerCase();
  return hay.includes(state.query);
}

function visibleSlugs() {
  return state.slugs.filter((s) => matches(state.catalog[s]));
}

/* ---------- library grid ---------- */

function makeBadge(rt) {
  const b = document.createElement("span");
  b.className = `badge ${runtimeClass(rt)}`;
  b.textContent = rt;
  return b;
}

function makeCard(slug) {
  const e = state.catalog[slug];
  const card = document.createElement("a");
  card.className = "card";
  card.href = `#${slug}`;
  card.setAttribute("aria-label", `${e.name} (${e.runtime})`);

  const img = document.createElement("img");
  img.loading = "lazy";
  img.alt = "";
  img.src = e.hero || LUTRIS_BANNER(slug);
  img.addEventListener("error", () => {
    img.replaceWith(
      Object.assign(document.createElement("div"), {
        className: "fallback",
        textContent: e.name,
      }),
    );
  });
  card.appendChild(img);

  const meta = document.createElement("div");
  meta.className = "overlay-meta";
  const title = document.createElement("span");
  title.className = "title";
  title.textContent = e.name;
  meta.append(title, makeBadge(e.runtime));
  card.appendChild(meta);
  return card;
}

function renderLibrary() {
  const slugs = visibleSlugs();
  el.count.textContent = `${slugs.length} / ${state.slugs.length} games`;
  el.library.replaceChildren();
  if (slugs.length === 0) {
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = "No games match your search.";
    el.library.appendChild(p);
    return;
  }
  const frag = document.createDocumentFragment();
  for (const slug of slugs) frag.appendChild(makeCard(slug));
  el.library.appendChild(frag);
}

function renderFilters() {
  const present = new Set(state.slugs.map((s) => state.catalog[s].runtime));
  const order = ["all", ...RUNTIMES.filter((r) => present.has(r))];
  for (const r of present) if (!order.includes(r)) order.push(r);

  el.filters.replaceChildren();
  for (const rt of order) {
    const chip = document.createElement("button");
    chip.className = "chip";
    chip.type = "button";
    chip.textContent = rt;
    chip.setAttribute("aria-pressed", String(rt === state.runtime));
    chip.addEventListener("click", () => {
      state.runtime = rt;
      renderFilters();
      renderLibrary();
    });
    el.filters.appendChild(chip);
  }
}

/* ---------- detail view ---------- */

function metaRow(e) {
  const row = document.createElement("div");
  row.className = "meta-row";
  const parts = [];
  parts.push(makeBadge(e.runtime));
  if (e.year) parts.push(textSpan(String(e.year)));
  if (e.genres && e.genres.length) parts.push(textSpan(e.genres.join(", ")));
  if (e.developers && e.developers.length)
    parts.push(textSpan(e.developers.join(", ")));
  parts.forEach((node, i) => {
    if (i > 0) {
      const dot = document.createElement("span");
      dot.className = "dot";
      dot.textContent = "•";
      row.appendChild(dot);
    }
    row.appendChild(node);
  });
  return row;
}

function textSpan(t) {
  const s = document.createElement("span");
  s.textContent = t;
  return s;
}

function openLightbox(src) {
  el.lightboxImg.src = src;
  el.lightbox.hidden = false;
}

function makeShots(e) {
  if (!e.screenshots || e.screenshots.length === 0) return null;
  const wrap = document.createElement("div");
  wrap.className = "shots";
  for (const src of e.screenshots) {
    const img = document.createElement("img");
    img.loading = "lazy";
    img.src = src;
    img.alt = `${e.name} screenshot`;
    img.tabIndex = 0;
    img.addEventListener("click", () => openLightbox(src));
    img.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter" || ev.key === " ") {
        ev.preventDefault();
        openLightbox(src);
      }
    });
    wrap.appendChild(img);
  }
  return wrap;
}

function renderDetail(slug) {
  const e = state.catalog[slug];
  el.detail.replaceChildren();
  el.detail.dataset.open = "1";
  el.detail.hidden = false;
  el.library.hidden = true;
  el.filters.hidden = true;

  const hero = document.createElement("div");
  hero.className = "detail-hero";
  hero.style.backgroundImage = `url("${e.hero || LUTRIS_BANNER(slug)}")`;

  const back = document.createElement("button");
  back.className = "detail-back";
  back.type = "button";
  back.textContent = "← Library";
  back.addEventListener("click", () => {
    location.hash = "";
  });
  hero.appendChild(back);
  el.detail.appendChild(hero);

  const body = document.createElement("div");
  body.className = "detail-body";

  const h1 = document.createElement("h1");
  h1.textContent = e.name;
  body.appendChild(h1);
  body.appendChild(metaRow(e));

  const play = document.createElement("button");
  play.className = "play";
  play.type = "button";
  play.textContent = "Play";
  play.addEventListener("click", () => launch(slug, e.name));
  body.appendChild(play);

  if (e.short) {
    const p = document.createElement("p");
    p.className = "short";
    p.textContent = e.short;
    body.appendChild(p);
  }
  if (e.long && e.long !== e.short) {
    const p = document.createElement("p");
    p.className = "long";
    p.textContent = e.long;
    body.appendChild(p);
  }
  const shots = makeShots(e);
  if (shots) body.appendChild(shots);

  el.detail.appendChild(body);
  back.focus();
  window.scrollTo(0, 0);
}

function closeDetail() {
  el.detail.hidden = true;
  el.detail.dataset.open = "0";
  el.library.hidden = false;
  el.filters.hidden = false;
}

/* ---------- launch ---------- */

function launch(slug, name) {
  el.overlayTitle.textContent = `Launching ${name}…`;
  el.overlay.hidden = false;
  el.overlayClose.focus();
  // Hand off to the XDG scheme handler. Fire-and-forget: the browser cannot
  // observe the nix download/build, so progress is shown in the native
  // launcher window spawned by pkgs/strom-launch.
  window.location.href = `strom://${encodeURIComponent(slug)}`;
}

function closeOverlay() {
  el.overlay.hidden = true;
}

/* ---------- routing ---------- */

function router() {
  const slug = decodeURIComponent(location.hash.replace(/^#/, ""));
  if (slug && state.catalog[slug]) {
    renderDetail(slug);
  } else {
    closeDetail();
  }
}

/* ---------- init ---------- */

function wireEvents() {
  el.search.addEventListener("input", () => {
    state.query = el.search.value.trim().toLowerCase();
    renderLibrary();
  });
  el.overlayClose.addEventListener("click", closeOverlay);
  el.lightbox.addEventListener("click", () => {
    el.lightbox.hidden = true;
    el.lightboxImg.src = "";
  });
  document.addEventListener("keydown", (ev) => {
    if (ev.key !== "Escape") return;
    if (!el.lightbox.hidden) {
      el.lightbox.hidden = true;
      el.lightboxImg.src = "";
    } else if (!el.overlay.hidden) {
      closeOverlay();
    } else if (el.detail.dataset.open === "1") {
      location.hash = "";
    }
  });
  window.addEventListener("hashchange", router);
}

async function init() {
  try {
    state.catalog = await loadCatalog();
  } catch (err) {
    el.library.innerHTML = "";
    const p = document.createElement("p");
    p.className = "empty";
    p.textContent = `Failed to load catalog: ${err.message}`;
    el.library.appendChild(p);
    return;
  }
  state.slugs = Object.keys(state.catalog).sort((a, b) =>
    state.catalog[a].name.localeCompare(state.catalog[b].name),
  );
  renderFilters();
  renderLibrary();
  wireEvents();
  router();
}

init();
