{
  lib,
  runCommand,
  writeShellApplication,
  python3,
  xdg-utils,
}:

# `strom-gui` serves the static web catalog (web/gui + the generated
# catalog.json/games.json) over a localhost HTTP server and opens it in the
# browser. It is deliberately a dumb static file server, not an application
# daemon: launching a game is handed off to the `strom://` URI scheme (see
# pkgs/strom-launch), so the GUI itself needs no privileges and no game closure.

let
  webSrc = ../../web;

  # Assemble the served document root. catalog.json is generated by
  # scripts/fetch-steam-metadata.py and committed; copy it when present and
  # always fall back to games.json (which the SPA also understands).
  bundle = runCommand "strom-gui-web" { } ''
    mkdir -p "$out/gui"
    cp ${webSrc}/gui/index.html ${webSrc}/gui/app.js ${webSrc}/gui/style.css "$out/gui/"
    cp ${webSrc}/games.json "$out/games.json"
    if [ -e ${webSrc}/catalog.json ]; then
      cp ${webSrc}/catalog.json "$out/catalog.json"
    fi
  '';
in
writeShellApplication {
  name = "strom-gui";
  runtimeInputs = [
    python3
    xdg-utils
  ];
  text = ''
    root=${bundle}
    port="''${STROM_GUI_PORT:-8731}"
    url="http://127.0.0.1:''${port}/gui/index.html"

    python3 -m http.server "$port" --bind 127.0.0.1 --directory "$root" &
    server=$!
    trap 'kill "$server" 2>/dev/null || true' EXIT

    # Give the server a beat to bind before pointing the browser at it.
    sleep 0.5
    echo "strom-gui serving $url" >&2
    xdg-open "$url" >/dev/null 2>&1 || echo "open $url manually" >&2

    wait "$server"
  '';
  meta = {
    description = "Steam-like web catalog browser for strom games";
    mainProgram = "strom-gui";
    platforms = lib.platforms.linux;
  };
}
