{
  buildFHSEnv,
  fetchurl,
  innoextract,
  p7zip,
  pkgsi686Linux,
  proton-ge-bin,
  runCommandLocal,
  writeShellScript,
}:

let
  proton = proton-ge-bin.steamcompattool;

  gameInstaller = fetchurl {
    url = "https://archive.org/download/thief-2-hdmod-1.0_202404/Thief%20Gold%20%28GoG%29/setup_thief_gold.exe";
    hash = "sha256-V+y0sfql8sSEDeZXUZMfGfriurC438aGLZAh5KXFeIw=";
    name = "setup_thief_gold.exe";
  };

  tfixInstaller = fetchurl {
    url = "https://archive.org/download/thief-2-hdmod-1.0_202404/patches/TFix_1.27b%20ptr%20thief%201%20si%20gold.exe";
    hash = "sha256-Dpk+cO3k3cD5R873w5tKBNMCTj09P9VqZoH3Neeuqxw=";
    name = "tfix.exe";
  };

  gameFiles =
    runCommandLocal "thief-gold-data"
      {
        nativeBuildInputs = [
          innoextract
          p7zip
        ];
      }
      ''
            mkdir -p "$out"

            # Extract base GOG game
            innoextract -d "$out" ${gameInstaller}
            mv "$out/app"/* "$out"/
            rmdir "$out/app"

            # Apply TFix (NewDark engine patch) on top
            7z x -aoa -o"$out" ${tfixInstaller}

            # Clean up NSIS installer artifacts
            rm -rf "$out/\$PLUGINSDIR"

            # Create case-insensitive symlinks for paths referenced in configs
            ln -sf MOVIES "$out/movies"
            ln -sf RES "$out/res"

            # Modern WASD keybindings
            cat > "$out/DARK.BND" <<'BINDS'
        auto_equip 1
        bow_zoom 1
        mouse_invert 0
        lookspring 0
        freelook 1
        mouse_sensitivity 3.0

        bind shift +creepon
        bind ctrl +slideon

        bind w +walkfast
        bind s +backfast
        bind a +moveleftfast
        bind d +moverightfast

        bind up +walkfast
        bind down +backfast
        bind left +moveleftfast
        bind right +moverightfast

        bind q +leanleft
        bind e +leanright
        bind r +leanforward

        bind c crouch
        bind space +jumpblock

        bind mouse1 +use_weapon
        bind mouse2 +use_item
        bind mouse3 +block
        bind mouse_axisx mturn
        bind mouse_axisy mlook

        bind f drop_item

        bind tab "cycle_item 1"
        bind tab+shift "cycle_item -1"
        bind ] "cycle_item 1"
        bind [ "cycle_item -1"

        bind backspace clear_item
        bind ` clear_weapon
        bind ~ clear_weapon
        bind 1 "inv_select sword"
        bind 2 "inv_select blackjack"
        bind 3 "inv_select broadhead"
        bind 4 "inv_select water"
        bind 5 "inv_select firearr"
        bind 6 "inv_select EarthArrow"
        bind 7 "inv_select GasArrow"
        bind 8 "inv_select RopeArrow"
        bind 9 "inv_select noise"

        bind F5  quick_save
        bind F9  quick_load
        bind F10 screen_dump

        bind m automap
        bind o objectives

        bind ESC sim_menu

        bind - "gamma_delta 0.025"
        bind + "gamma_delta -0.025"
        bind = "gamma_delta -0.025"
        BINDS

            # Create install.cfg (normally generated by the NSIS installer)
            cat > "$out/install.cfg" <<'EOF'
        ;cd_path .\
        install_path .\
        language english
        resname_base .\patches+.\tgpatch+.\res
        load_path .\patches+.\
        script_module_path .\
        movie_path .\movies
        EOF

            # Override cam_ext.cfg for Wine/Proton compatibility
            cat > "$out/cam_ext.cfg" <<'EXTCFG'
        use_d3d_display
        force_windowed
        force_32bit
        force_32bit_textures
        skip_starting_checks
        new_mantle
        enhanced_sky 1
        z_far 512
        game_screen_size 1920 1080
        mipmap_mode 2
        lm_mipmap_mode 0
        lm_init_texmem 2
        lm_filter_margin 1
        tex_edge_padding 2
        alpha_test_as_opaque
        d3d_disp_no_rgb10_buf
        wr_render_zcomp
        render_weapon_particles
        dark_zcomp_arm
        ObjTextures16
        MeshTextures16
        framerate_cap 60.0
        phys_freq 60
        min_frame_time 1
        d3d_disp_limit_gpu_frames 1 1
        sfx_device 2
        sfx_channels 32
        sfx_eax 1
        eax_environment 1
        EXTCFG
      '';

  wrapper = writeShellScript "thief-gold-wrapper" ''
        set -euo pipefail

        GAMEDIR="''${HOME:-.}/.strom/thief-gold"
        COMPATDATA="$GAMEDIR/211600"
        mkdir -p "$GAMEDIR" "$COMPATDATA"

        # Recursively symlink game files, creating real directories
        # so the game can write alongside read-only store files
        link_tree() {
          local src="$1" dst="$2"
          mkdir -p "$dst"
          for f in "$src"/*; do
            base="$(basename "$f")"
            if [ -d "$f" ]; then
              link_tree "$f" "$dst/$base"
            elif [ ! -e "$dst/$base" ] || [ -L "$dst/$base" ]; then
              ln -sf "$f" "$dst/$base"
            fi
          done
        }
        link_tree "${gameFiles}" "$GAMEDIR"

        # Ensure writable save directory (remove symlinked default saves)
        find "$GAMEDIR/SAVES" -maxdepth 1 -type l -delete 2>/dev/null || true
        mkdir -p "$GAMEDIR/SAVES"

        export STEAM_COMPAT_DATA_PATH="$COMPATDATA"
        export STEAM_COMPAT_CLIENT_INSTALL_PATH="$COMPATDATA"
        export STEAM_COMPAT_APP_ID="211600"


        # Ensure 32-bit and 64-bit libraries are discoverable by Wine/Proton
        export LD_LIBRARY_PATH="/usr/lib32:/usr/lib:/usr/lib64''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

        # DXVK d3d9 config
        cat > "$GAMEDIR/dxvk.conf" <<DXVKCONF
    d3d9.floatEmulation = strict
    d3d9.invariantPosition = True
    d3d9.memoryTrackTest = True
    DXVKCONF
        export DXVK_CONFIG_FILE="$GAMEDIR/dxvk.conf"
        export DXVK_ASYNC=1
        export DXVK_STATE_CACHE_PATH="$GAMEDIR"
        export STAGING_WRITECOPY=1
        export WINE_LARGE_ADDRESS_AWARE=1

        # OpenAL Soft config for low-latency EAX audio
        mkdir -p "$GAMEDIR/openal"
        cat > "$GAMEDIR/openal/alsoft.conf" <<ALCONF
    [general]
    drivers = pulse,alsa
    period-size = 1024
    periods = 4
    stereo-mode = speakers
    [pulse]
    allow-moves = true
    ALCONF
        export ALSOFT_CONF="$GAMEDIR/openal/alsoft.conf"
        export PULSE_LATENCY_MSEC=40

        cd "$GAMEDIR"

        gamescope -W 1920 -H 1080 -w 1920 -h 1080 -r 60 --immediate-flips --expose-wayland -- \
          python3 "${proton}/proton" waitforexitandrun "$GAMEDIR/Thief.exe" || true
  '';
in
buildFHSEnv {
  name = "thief-gold";
  runScript = wrapper;

  targetPkgs = pkgs: [
    pkgs.freetype
    pkgs.glibc
    pkgs.gamescope
    pkgs.python3
    # Vulkan/OpenGL drivers
    pkgs.mesa
    pkgs.vulkan-loader
    pkgs.libGL
    # X11 libraries (64-bit, needed by Wine's display driver)
    pkgs.libx11
    pkgs.libxext
    pkgs.libxcb
    pkgs.libxcursor
    pkgs.libxrandr
    pkgs.libxi
    pkgs.libxfixes
    pkgs.libxrender
    pkgs.libxcomposite
    pkgs.libxinerama
    pkgs.libxxf86vm
    pkgs.libxau
    pkgs.libxdmcp
    # Audio
    pkgs.alsa-lib
    pkgs.libpulseaudio
    pkgs.openal
    # 32-bit libraries needed by Wine/Proton for 32-bit games
    pkgsi686Linux.freetype
    pkgsi686Linux.glibc
    pkgsi686Linux.glib
    pkgsi686Linux.libx11
    pkgsi686Linux.libxext
    pkgsi686Linux.libxcb
    pkgsi686Linux.libxcursor
    pkgsi686Linux.libxrandr
    pkgsi686Linux.libxi
    pkgsi686Linux.libxfixes
    pkgsi686Linux.libxrender
    pkgsi686Linux.libxcomposite
    pkgsi686Linux.libxinerama
    pkgsi686Linux.libxxf86vm
    pkgsi686Linux.libxau
    pkgsi686Linux.libxdmcp
    pkgsi686Linux.libGL
    pkgsi686Linux.mesa
    pkgsi686Linux.vulkan-loader
    pkgsi686Linux.openal
    pkgsi686Linux.alsa-lib
    pkgsi686Linux.libpulseaudio
  ];

  meta = {
    description = "Thief Gold with TFix (NewDark engine, via Proton and gamescope)";
    platforms = [ "x86_64-linux" ];
    mainProgram = "thief-gold";
  };
}
