{
  buildFHSEnv,
  fetchurl,
  innoextract,
  p7zip,
  pkgsi686Linux,
  proton-ge-bin,
  runCommandLocal,
  writeShellScript,
}:

let
  proton = proton-ge-bin.steamcompattool;

  gameInstaller = fetchurl {
    url = "https://archive.org/download/thief-2-hdmod-1.0_202404/Thief%20Gold%20%28GoG%29/setup_thief_gold.exe";
    hash = "sha256-V+y0sfql8sSEDeZXUZMfGfriurC438aGLZAh5KXFeIw=";
    name = "setup_thief_gold.exe";
  };

  tfixInstaller = fetchurl {
    url = "https://archive.org/download/thief-2-hdmod-1.0_202404/patches/TFix_1.27b%20ptr%20thief%201%20si%20gold.exe";
    hash = "sha256-Dpk+cO3k3cD5R873w5tKBNMCTj09P9VqZoH3Neeuqxw=";
    name = "tfix.exe";
  };

  gameFiles = runCommandLocal "thief-gold-data" {
    nativeBuildInputs = [
      innoextract
      p7zip
    ];
  } ''
    mkdir -p "$out"

    # Extract base GOG game
    innoextract -d "$out" ${gameInstaller}
    mv "$out/app"/* "$out"/
    rmdir "$out/app"

    # Apply TFix (NewDark engine patch) on top
    7z x -aoa -o"$out" ${tfixInstaller}

    # Clean up NSIS installer artifacts
    rm -rf "$out/\$PLUGINSDIR"

    # Create case-insensitive symlinks for paths referenced in configs
    ln -sf MOVIES "$out/movies"
    ln -sf RES "$out/res"

    # Create install.cfg (normally generated by the NSIS installer)
    cat > "$out/install.cfg" <<'EOF'
;cd_path .\
install_path .\
language english
resname_base .\patches+.\tgpatch+.\res
load_path .\patches+.\
script_module_path .\
movie_path .\movies
EOF

    # Override cam_ext.cfg for Wine/Proton compatibility
    cat > "$out/cam_ext.cfg" <<'EXTCFG'
use_d3d_display
force_windowed
force_32bit
skip_starting_checks
new_mantle
enhanced_sky 1
z_far 512
game_screen_size 1920 1080
EXTCFG
  '';

  wrapper = writeShellScript "thief-gold-wrapper" ''
    set -euo pipefail

    GAMEDIR="''${HOME:-.}/.thief-gold"
    COMPATDATA="$GAMEDIR/211600"
    mkdir -p "$GAMEDIR" "$COMPATDATA"

    # Recursively symlink game files, creating real directories
    # so the game can write alongside read-only store files
    link_tree() {
      local src="$1" dst="$2"
      mkdir -p "$dst"
      for f in "$src"/*; do
        base="$(basename "$f")"
        if [ -d "$f" ]; then
          link_tree "$f" "$dst/$base"
        elif [ ! -e "$dst/$base" ] || [ -L "$dst/$base" ]; then
          ln -sf "$f" "$dst/$base"
        fi
      done
    }
    link_tree "${gameFiles}" "$GAMEDIR"

    # Ensure writable save directory (remove symlinked default saves)
    find "$GAMEDIR/SAVES" -maxdepth 1 -type l -delete 2>/dev/null || true
    mkdir -p "$GAMEDIR/SAVES"

    export STEAM_COMPAT_DATA_PATH="$COMPATDATA"
    export STEAM_COMPAT_CLIENT_INSTALL_PATH="$COMPATDATA"
    export STEAM_COMPAT_APP_ID="211600"


    # Ensure 32-bit and 64-bit libraries are discoverable by Wine/Proton
    export LD_LIBRARY_PATH="/usr/lib32:/usr/lib:/usr/lib64''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

    cd "$GAMEDIR"

    exec gamescope -W 1920 -H 1080 -w 1920 -h 1080 -- \
      python3 "${proton}/proton" waitforexitandrun "$GAMEDIR/Thief.exe"
  '';
in
buildFHSEnv {
  name = "thief-gold";
  runScript = wrapper;

  targetPkgs = pkgs: [
    pkgs.freetype
    pkgs.glibc
    pkgs.gamescope
    pkgs.python3
    # Vulkan/OpenGL drivers
    pkgs.mesa
    pkgs.vulkan-loader
    pkgs.libGL
    # X11 libraries (64-bit, needed by Wine's display driver)
    pkgs.libx11
    pkgs.libxext
    pkgs.libxcb
    pkgs.libxcursor
    pkgs.libxrandr
    pkgs.libxi
    pkgs.libxfixes
    pkgs.libxrender
    pkgs.libxcomposite
    pkgs.libxinerama
    pkgs.libxxf86vm
    pkgs.libxau
    pkgs.libxdmcp
    # Audio
    pkgs.alsa-lib
    pkgs.libpulseaudio
    pkgs.openal
    # 32-bit libraries needed by Wine/Proton for 32-bit games
    pkgsi686Linux.freetype
    pkgsi686Linux.glibc
    pkgsi686Linux.glib
    pkgsi686Linux.libx11
    pkgsi686Linux.libxext
    pkgsi686Linux.libxcb
    pkgsi686Linux.libxcursor
    pkgsi686Linux.libxrandr
    pkgsi686Linux.libxi
    pkgsi686Linux.libxfixes
    pkgsi686Linux.libxrender
    pkgsi686Linux.libxcomposite
    pkgsi686Linux.libxinerama
    pkgsi686Linux.libxxf86vm
    pkgsi686Linux.libxau
    pkgsi686Linux.libxdmcp
    pkgsi686Linux.libGL
    pkgsi686Linux.mesa
    pkgsi686Linux.vulkan-loader
    pkgsi686Linux.openal
    pkgsi686Linux.alsa-lib
    pkgsi686Linux.libpulseaudio
  ];

  meta = {
    description = "Thief Gold with TFix (NewDark engine, via Proton and gamescope)";
    platforms = [ "x86_64-linux" ];
    mainProgram = "thief-gold";
  };
}
